# Generated by Django 5.1 on 2024-09-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_author_delete_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
