# Generated by Django 5.1 on 2024-09-01 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_id_book_b_id_alter_bookuser_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='b_id',
            new_name='id',
        ),
    ]
